### ISSUE TITLE
Synthext 150k?

### ISSUE THREAD

**Issue by zobeirraisi** [Yuliang-Liu/bezier_curve_text_spotting#1]
Thanks for your wonderful work,
When the Syntext-150k dataset will be available?
Have you trained your recognition part with special characters?

**Comment by Yuliang-Liu** [comment]
Soon. Yes.

**Comment by zobeirraisi** [comment]
> Soon. Yes.

Thanks for sharing.

**Comment by Yuliang-Liu** [comment]
Thanks for your attention.

**Comment by maliho0803** [comment]
will you release code of generating curve texts?
