### ISSUE TITLE
Public total_train.json

### ISSUE THREAD

**Issue by nguyennm1024** [Yuliang-Liu/bezier_curve_text_spotting#10]
Dear author,

I want to try to train your model with total text dataset. Can you please give me total_train.json file to do that.

Thank you

**Comment by Yuliang-Liu** [comment]
We will release our full code in the [Adet](https://github.com/aim-uofa/AdelaiDet) next week, including the models of CTW1500 and Total-text, all the training data we used, evaluation scripts, results of detection, etc. More updates will also be conducted on [Adet](https://github.com/aim-uofa/AdelaiDet) as well. This repo will not be maintained anymore.

Thanks for your attention.
