### ISSUE TITLE
When I run vis_bezier.py,  The following error appeared.

### ISSUE THREAD

**Issue by jiyuxuan926** [Yuliang-Liu/bezier_curve_text_spotting#11]
File "D:\ocr_demo\bezier_curve_text_spotting-master\maskrcnn_benchmark\layers\nms.py", line 8, in <module>
    nms = amp.float_function(_C.nms)
  File "D:\Anaconda\envs\pytorch_gpu\lib\site-packages\yacs\config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: nms

**Comment by jiyuxuan926** [comment]
from maskrcnn_benchmark import _C

**Comment by ran337287** [comment]
> from maskrcnn_benchmark import _C

I met the same problem, have you solved it?

**Comment by jiyuxuan926** [comment]
> > from maskrcnn_benchmark import _C
> 
> I met the same problem, have you solved it?

no yet

**Comment by jiyuxuan926** [comment]
> > from maskrcnn_benchmark import _C
> 
> I met the same problem, have you solved it?

It may be related to the pytorch version, which I have not solved yet.

**Comment by Yuliang-Liu** [comment]
We will release our full code in the [Adet](https://github.com/aim-uofa/AdelaiDet) next week, including the models of CTW1500 and Total-text, all the training data we used, evaluation scripts, results of detection, etc. More updates will also be conducted on [Adet](https://github.com/aim-uofa/AdelaiDet) as well. This repo will not be maintained anymore.

Thanks for your attention.
