### ISSUE TITLE
框架及中文模型训练疑问

### ISSUE THREAD

**Issue by lmw0320** [Yuliang-Liu/bezier_curve_text_spotting#13]
你好~~
想请教几点问题：
1. 我需要训练中文检测+识别模型，来进行证照文件的识别。这份代码是在pytorch框架下的，可以直接拿来训练模型么？
2. 如可以，是否有预训练模型呢，可以方便我节省一定的训练时间。
3. 证照文件中，同时含有水平文字、倾斜文本和环形文本，这个模型，可以自动进行相应的识别？？
3. 中文包含生僻字。。这种情况下，数据集貌似只能自己手动标注么，没办法合成？ ---ctw数据集貌似只有不到4K个汉字字符，无法满足使用要求。。
恳请博主指点迷津~~

**Comment by Yuliang-Liu** [comment]
Hi there,

1. Yes. It can be used for training, but I recommend to use the AdelaiDet version. 
2. I will provide the Chinese pretrained model later. (AdelaiDet version)
3. Yes, it can be used for arbitrarily shaped text of the license files.
4. You can synthesize the Chinese text by yourself. There are many public Chinese datasets such ArT, LSVT, and ReCTS.

**Comment by lmw0320** [comment]
> Hi there,
> 
> 1. Yes. It can be used for training, but I recommend to use the AdelaiDet version.
> 2. I will provide the Chinese pretrained model later. (AdelaiDet version)
> 3. Yes, it can be used for arbitrarily shaped text of the license files.
> 4. You can synthesize the Chinese text by yourself. There are many public Chinese datasets such ArT, LSVT, and ReCTS.

Thanks for your reply. I will check the details first . If any further queries, I will ask later :)
