### ISSUE TITLE
text detection performance results

### ISSUE THREAD

**Issue by HumanZhong** [Yuliang-Liu/bezier_curve_text_spotting#3]
Thanks for your great work and sharing the code.
The text detection results are not available on your arxiv paper, so can you provide the text detection results(Recall/Precision/F-measure) on your datasets(CTW1500, Total-Text, etc.) if possible? Thanks a lot.

**Comment by Yuliang-Liu** [comment]
Hi Zhong, 

We find that a better e2e results may cause a worse detection result. Anyway, we will provide that as soon as possible.

**Comment by deepseek** [comment]
> a better e2e results may cause a worse detection result.

Explain

**Comment by ghost** [comment]
@Yuliang-Liu What are the results on icdar2015

**Comment by Yuliang-Liu** [comment]
We will release our full code in the [Adet](https://github.com/aim-uofa/AdelaiDet) next week, including the models of CTW1500 and Total-text, the training data we used, evaluation scripts, results of detection, etc. More updates will also be conducted on [Adet](https://github.com/aim-uofa/AdelaiDet) as well. This repo will not be maintained anymore.

Thanks for your attention.
