### ISSUE TITLE
Detectron2 and AdelaiDet

### ISSUE THREAD

**Issue by ghost** [Yuliang-Liu/bezier_curve_text_spotting#4]
@Yuliang-Liu @stan-haochen 
Thank you for open-sourcing your hard work,

Regarding the ABCNet implementation in Detectron2, when do you expect releasing that.
Also, further documentation on how to train ABCNet.

**Comment by stan-haochen** [comment]
Hi @deepseek ! We will release the training code in AdelaiDet alongside the CVPR conference. Should be available in about two months.

**Comment by ghost** [comment]
Thanks!!!
take care!
