### ISSUE TITLE
icdar2015

### ISSUE THREAD

**Issue by ghost** [Yuliang-Liu/bezier_curve_text_spotting#6]
@Yuliang-Liu 
Include icdar2015 dataloader for training and predicting

**Comment by Yuliang-Liu** [comment]
We will release our full code in the Adet next week, including the models of CTW1500 and Total-text, the training data we used, evaluation scripts, results of detection, etc. More updates will also be conducted on Adet as well. This repo will not be maintained anymore.

Thanks for your attention.
