### ISSUE TITLE
Trained Model for evaluation

### ISSUE THREAD

**Issue by royadityak94** [Yuliang-Liu/bezier_curve_text_spotting#7]
Hi, Can you provide the trained model google drive link and a small demo of how to use to make inferences? It will be really wonderful to see its performance in practice.

**Comment by stan-haochen** [comment]
Hi @royadityak94 . We will release the trained models in short future. We expect them to be available when the CVPR conference is held.

**Comment by Yuliang-Liu** [comment]
We will release our full code in the Adet next week, including the models of CTW1500 and Total-text, the training data we used, evaluation scripts, results of detection, etc. More updates will also be conducted on Adet as well. This repo will not be maintained anymore.

Thanks for your attention.
