### ISSUE TITLE
results ?

### ISSUE THREAD

**Issue by trungpham2606** [Yuliang-Liu/bezier_curve_text_spotting#8]
@Yuliang-Liu 
Tks for sharing such a great work
iam having a question about the cps: in single_demo_bezier.py, how to get those values, cause when i tried with different images, the network cant output the text scene correctly.
And when I tried to use vis_bezier.py, the results are not good as yours:
![image](https://user-images.githubusercontent.com/35657426/78544857-fdc62b00-7824-11ea-8acf-669aeb0e28f3.png)
![image](https://user-images.githubusercontent.com/35657426/78544933-1afaf980-7825-11ea-9b0f-fe818281970e.png)

Which parameters should I change to get the same result as yours ?

**Comment by Yuliang-Liu** [comment]
We will release our full code in the Adet next week, including the models of CTW1500 and Total-text, the training data we used, evaluation scripts, results of detection, etc. More updates will also be conducted on Adet as well. This repo will not be maintained anymore.

Thanks for your attention.
